#!/bin/env bash

oneKittyInstance() {
        return $(pgrep kitty | wc -w | awk '{print $1>=2}')
}

if oneKittyInstance; then
        # if there is one instance of kitty
        tmux new -As0 "$@"
else
        # if there is more than one instance of kitty
        tmux "$@"
fi
